name: 'limgo'
description: 'Do not let your test coverage drop'
branding:
  color: orange
  icon: check-circle
inputs:
  version:
    description: 'limgo version'
    required: false
    default: 'latest'
  args:
    description: 'Arguments to pass to limgo'
    required: false
  install-only:
    description: 'Just install limgo'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
  